language: bash

script:
- tar -cJf openstack.txz tools/ Makefile.openstack Makefile.vm

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: openstack.txz
  skip_cleanup: true
  on:
    tags: true